default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: app_database
  host: db
  user: postgres
  password:

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default